from enum import Enum

class LanguageCode(Enum):
    EN_US = "en-US"
    EN_GB = "en-GB"
    ES_ES = "es-ES"
    ES_MX = "es-MX"
    FR_FR = "fr-FR"
    FR_CA = "fr-CA"
    DE_DE = "de-DE"
    IT_IT = "it-IT"
    PT_PT = "pt-PT"
    PT_BR = "pt-BR"
    ZH_CN = "zh-CN"
    ZH_TW = "zh-TW"
    JA_JP = "ja-JP"
    KO_KR = "ko-KR"
    RU_RU = "ru-RU"
    AR_SA = "ar-SA"
    HI_IN = "hi-IN"
    PL_PL = "pl-PL"